# Generated by Django 3.2.16 on 2025-05-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Месяц показания')),
                ('reading', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Показание')),
            ],
            options={
                'verbose_name': 'Показание счётчика',
                'verbose_name_plural': 'Показания счётчиков',
            },
        ),
        migrations.CreateModel(
            name='Meters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual_number', models.CharField(max_length=50, unique=True, verbose_name='Индивидуальный номер')),
            ],
            options={
                'verbose_name': 'Счётчик',
                'verbose_name_plural': 'Счётчики',
            },
        ),
        migrations.CreateModel(
            name='PaymentRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оплачено (руб.)')),
                ('payment_date', models.DateField(verbose_name='Месяц оплаты')),
            ],
            options={
                'verbose_name': 'Запись об оплате',
                'verbose_name_plural': 'Записи об оплате',
            },
        ),
        migrations.CreateModel(
            name='Utilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('tariff', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Тариф')),
                ('units', models.CharField(blank=True, max_length=10, null=True, verbose_name='Единицы измерения')),
                ('norm', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Норматив')),
            ],
            options={
                'verbose_name': 'Коммунальная услуга',
                'verbose_name_plural': 'Коммунальные услуги',
            },
        ),
    ]
