# Generated by Django 3.2.16 on 2025-05-23 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building_service', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecords',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='users.personalaccount', verbose_name='Лицевой счет'),
        ),
        migrations.AddField(
            model_name='paymentrecords',
            name='utility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='building_service.utilities', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='meters',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='users.personalaccount', verbose_name='Лицевой счет'),
        ),
        migrations.AddField(
            model_name='meters',
            name='utility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='building_service.utilities', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='meterreadings',
            name='meter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='building_service.meters', verbose_name='Счетчик'),
        ),
    ]
